// Runtime-free DB types (moved out of ORM-specific artifacts). These
// types are the canonical shapes used throughout the codebase.

export type NutritionSummary = any; // kept broad for now (was generated by AI)

export type ShoppingItem = {
  name: string;
  quantity?: string;
  notes?: string;
};

export type ShoppingList = {
  id: number;
  userId: number;
  items: ShoppingItem[];
  isCompleted: number;
  createdAt: Date;
  updatedAt: Date;
};

export type DayMenu = Record<string, any>;

export type UserPreferences = {
  id: number;
  userId: number;
  allergies: string[];
  dietaryRestrictions: string[];
  nutritionalGoals: string[];
  preferredCuisines: string[];
  dislikedIngredients: string[];
  targetCalories: number;
  targetProtein: number;
  targetCarbs: number;
  targetFat: number;
  mealsPerDay: number;
  includeSnacks: number;
  createdAt: Date;
  updatedAt: Date;
};

export type InsertUserPreferences = Omit<UserPreferences, 'id' | 'userId' | 'createdAt' | 'updatedAt'>;

export type User = {
  id: number;
  openId: string;
  name?: string | null;
  email?: string | null;
  loginMethod?: string | null;
  role: 'user' | 'admin';
  // Password column is optional in newer schema but many installs have it —
  // keep it in the type so the server can work with legacy DBs.
  password?: string | null;
  createdAt: Date;
  updatedAt: Date;
  lastSignedIn: Date;
};

export type InsertUser = Partial<User> & { openId: string };

export type InsertWeeklyMenu = {
  userId: number;
  menuData: Record<string, DayMenu>;
  nutritionSummary: NutritionSummary;
  startDate: Date;
  isActive?: number;
  notes?: string | null;
};

export type WeeklyMenu = InsertWeeklyMenu & { id: number; createdAt: Date; updatedAt: Date };

export type InsertShoppingList = { weeklyMenuId: number; userId: number; items: ShoppingItem[]; isCompleted?: number };
